post_install do |installer|
  installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      end
  end
end

target 'Dobby' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Reactive X
  pod 'RxCocoa'
  pod 'RxDataSources'
  pod 'RxOptional'
  pod 'RxSwift'
  pod 'RxViewController'
  pod 'RxGesture'
  
  # UI
  pod 'SnapKit'
  pod 'lottie-ios'
  pod 'Kingfisher'
  
  # Toast
  pod 'Toast-Swift'
  
  # Network
  pod 'Moya/RxSwift'
  
  # Logging
  pod 'SwiftyBeaver'
  
  # Lint
  pod 'SwiftLint'
  
  # KakaoSDK
  pod 'RxKakaoSDK'
  
  # Firebase
  pod 'FirebaseCrashlytics'
  pod 'FirebaseAnalytics'

  target 'DobbyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DobbyUITests' do
    # Pods for testing
  end

end
