post_install do |installer|
  installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      end
  end
end

target 'Dobby' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Dobby

  # RX
  pod 'RxCocoa'
  pod 'RxDataSources'
  pod 'RxOptional'
  pod 'RxSwift'
  pod 'RxViewController'
  pod 'RxGesture'
  
  # frameWork
  pod 'SnapKit'
  pod 'lottie-ios'
  pod 'Kingfisher'
  pod 'ProgressHUD'
  pod 'Toast-Swift'
  pod 'FSCalendar'
  
  # Network
  pod 'Moya/RxSwift'
  pod 'Moya/Combine'
  
  # Logging
  pod 'SwiftyBeaver'
  
  # Lint
  pod 'SwiftLint'
  
  # KakaoSDK
  pod 'RxKakaoSDK'
  
  # Firebase
  pod 'FirebaseCrashlytics'
  pod 'FirebaseAnalytics'
  pod 'FirebaseMessaging'

  target 'DobbyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DobbyUITests' do
    # Pods for testing
  end

end

target 'DobbyMini' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DobbyMini

  target 'DobbyMiniTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DobbyMiniUITests' do
    # Pods for testing
  end

end

target 'DobbyMini WatchKit Extension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DobbyMini WatchKit Extension

  # Dependency Injection
  pod 'Swinject'

  # RX
  pod 'RxSwift'

  # Network
  pod 'Moya/RxSwift'
  pod 'Moya/Combine'
  
  # Logging
  pod 'SwiftyBeaver'

end
